media:
  input: public/media
  output: /media

content:
  - name: data
    label: Website Data
    path: src/content/data.json # Everything is stored in this ONE file
    type: file
    fields:
      # 1. The Blog Section (List of posts)
      - name: posts
        label: Blog Posts
        type: list # This allows you to append new items to the array
        item_label: "{{title}} - {{pubDate}}" # Helps identify posts in the CMS UI
        fields:
          - name: title
            label: Title
            type: string

          - name: description
            label: Description
            type: text

          - name: pubDate
            label: Publication Date
            type: date
            options:
              format: MM/dd/yyyy

          - name: updatedDate
            label: Last Updated Date
            type: date
            options:
              format: MM/dd/yyyy

          - name: heroImage
            label: Hero Image
            type: image

          - name: body
            label: Body
            type: rich-text

      # 2. The Site Settings Section (Single Object)
      - name: settings
        label: Site Settings
        type: object
        fields:
          - name: title
            label: Website title
            type: string

          - name: description
            label: Website description
            type: string
            description: Will be used for any page with no description.

          - name: url
            label: Website URL
            type: string
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$

          - name: cover
            label: Preview image
            type: image
            description: Image used in the social preview on social networks.