collections:
  projects:
    label: Projects
    path: content/projects.json
    format: json
    fields:
      - name: title
        label: Title
        type: text

      - name: description
        label: Description
        type: textarea

      - name: image
        label: Image URL
        type: text

      - name: link
        label: Project Link
        type: text
